# B-roll do "Burry x Barsi: o cobre" (gravado 27/09)
# (id, peca, ancora regex, atraso[, depois])  peca A = cartela | B = print (manchete / documento)
# ancora = regex no texto do segmento do RENDER (sem acento, minusculo)
# Denis (27/09): estilo Faz a Conta (traco + sons, sem palito); foco nas MANCHETES.
# Numeros da tela = roteiro atualizado 27/09 (placar ate 25/09): Ero 19,9 · PMAM 2,9 · dif 17,0
PECAS = [
 # ---------- BLOCO 0 — gancho ----------
 ("m1-burry-ero",   "B", r"mineradora que o michael burr",                 0.0),
 ("01-ero",         "A", r"valendo quase 20 mil",                     0.0),
 ("02-pmam",        "A", r"r\$ 2\.900",                            0.0),
 ("03-diferenca",   "A", r"diferenca chegou",                         0.0),
 ("m7-cobre-recorde",       "B", r"subiu para os dois, so que",     0.0),
 ("04-cobre-44",    "A", r"40% mais caro",                            0.0),
 ("05-duas-pontas", "A", r"numa dessas duas pontas",                  0.0),
 # ---------- BLOCO 1 — a estrada ----------
 ("06-grande-aposta","A", r"filme a grande aposta",                   0.0),
 ("d1-substack",    "B", r"ignorando a euforia",                        0.0),
 ("d1b-substack-cobre",      "A", r"cada vez mais bonito",                     0.0),
 ("09-estrada",     "A", r"saia de caminhao",                          0.0),
 ("10-fiado",       "A", r"fiado a receber",                          0.0),
 ("11-rj",          "A", r"recuperacao judicial e o prazo",           0.0),
 ("d2-pmam-2t26",   "B", r"refinou zero tonelada",                    0.0),
 ("12-550-zero",    "A", r"550 toneladas para zero",                  0.0),
 # ---------- BLOCO 2 — o socio do forno ----------
 ("d2b-pmam-hibernacao","B", r"forno da bahia esta desligado",          0.0),
 ("m2-pmam-rj",     "B", r"recuperacao judicial desde o fim",         0.0),
 ("m3-barsi-barco", "B", r"barco nao afundar",                        0.0),
 ("13-barsi-fatia", "A", r"tinha 5%",                                 0.0),
 ("d3-pmam-acionistas",  "B", r"lista de acionistas",                      0.0),
 ("m4b-conversao-divida","B", r"pagou o credor",                      0.0),
 ("14-diluicao",    "A", r"100 milhoes de acoes",                     0.0),
 ("m4-escoria",     "B", r"aceitou escoria",                          0.0),
 ("15-escoria",     "A", r"850 milhoes",                              0.0),
 ("16-carro",       "A", r"paga divida entregando",                   0.0),
 # ---------- BLOCO 3 — boi e acougue ----------
 ("17-boi-acougue", "A", r"dono do boi e o dono do acougue",          0.0),
 ("d4-ero-guidance",   "B", r"pouco mais de 2 dolares",                  0.0),
 ("18-cobre-683",   "A", r"esta quase 7 dolares",                  0.0),
 ("19-sobra",       "A", r"4 dolares e meio",                         0.0),
 ("20-picanha",     "A", r"picanha dobrou",                           0.0),
 ("21-premio",      "A", r"4 em cada 10 reais",                       0.0),
 ("22-balcao",      "A", r"foi o lado do balcao",                     0.0),
 # ---------- BLOCO 4 — a fazenda brasileira ----------
 ("23-vale-cobre",  "A", r"comprou vale achando",                     0.0),
 ("d5-vale-ebitda", "B", r"resultado de 2025",                        0.0),
 ("24-vale-4x",     "A", r"minerio de ferro deu quatro",                   0.0),
 ("25-placar-vale", "A", r"viraram r?\$? ?13",                        0.0),
 ("26-copx",        "A", r"40 minerador",                            0.0),
 ("27-bdr",         "A", r"bcpx39",                                   0.0),
 # ---------- PUBLI ----------
 ("28-div-30",      "A", r"30% ficam",                                0.0),
 ("29-isencao",     "A", r"nunca vendeu mais",                        0.0),
 ("d6-bdr-imposto", "B", r"15% em cima do lucro",                     0.0),
 ("30-grana",       "A", r"confere os seus darf",                     0.0),
 ("31-cupom",       "A", r"cupom desenrola",                          0.0),
 ("31-cupom@2",     "A", r"usa o cupom",                              0.0),
 # ---------- BLOCO 5 — predio e fiacao ----------
 ("m5-meme",        "B", r"vendido no predio",                        0.0),
 ("32-predio",      "A", r"o predio e o data center",                 0.0),
 ("33-18anos",      "A", r"18 anos",                                  0.0),
 ("m6-slok",        "B", r"gestora apollo",                           0.0),
 ("34-queda30",     "A", r"cair 30%",                                 0.0),
 ("35-metade",      "A", r"cai quase pela metade",                    0.0),
 # ---------- BLOCO 6 — a pergunta do boi ----------
 ("36-pergunta",    "A", r"pergunta do boi",                          0.0),
 ("37-p1",          "A", r"dona do boi ou",                           0.0),
 ("12-550-zero@2",  "A", r"zerado",                                   0.0),
 ("38-p2",          "A", r"quanto boi tem",                           0.0),
 ("39-p3",          "A", r"se a carne cair",                          0.0),
 ("40-boi-balcao",  "A", r"o boi ou o balcao",                            0.0),

 # ---------- 27/09 noite: preencher os buracos ----------
 ("x-whale",          "B", r"mineradora do burry mandava",            0.0),
 ("41-placar-qi",     "A", r"placar que mede",                         0.0),
 ("foto-cobre-cano",  "B", r"estatua verde",                           0.0),
 ("43-duas-minas",    "A", r"uma no para",                             0.0),
 ("foto-paranapanema","B", r"fundicao de quem",                        0.0),
 ("foto-cobre-catodo","B", r"o forno que derrete",                     0.0),
 ("44-fora-rj",       "A", r"e esse fiado ficou",         0.0),
 ("45-logica-barsi",  "A", r"a logica do v",                           0.0),
 ("46-diluicao",      "A", r"tal da diluicao",                         0.0),
 ("47-mesmo-ligado",  "A", r"mesmo ligado",                            0.0),
 ("48-dono-boi",      "A", r"se voce cria o boi",                      0.0),
 ("d4b-ero-titulo",   "B", r"e a dona do boi",                         0.0),
 ("49-custo-preco",   "A", r"custo 2 e pouco",                         0.0),
 ("50-acougue",       "A", r"acougueiro compra",                       0.0),
 ("51-corte",         "A", r"o que fica com ele",                      0.0),
 ("17-boi-acougue@2", "A", r"paranapanema, nesse caso, e o acougue",   0.0),
 ("x-bulltheory",     "B", r"negociada la fora",                       0.0),
 ("52-vale-boi",      "A", r"vale e dona de boi",                      0.0),
 ("53-voltou",        "A", r"voltou para casa",                        0.0),
 ("d6b-bdr-titulo",   "B", r"regra de imposto",                        0.0),
 ("54-div-inteiro",   "A", r"cai inteiro",                             0.0),
 ("55-darf",          "A", r"quem emite a guia",                       0.0),
 ("56-b3-grana",      "A", r"parceira e investidora",                  0.0),
 ("30-grana@2",       "A", r"paga ali mesmo",                          0.0),
 ("57-multa",         "A", r"pagar multa",                             0.0),
 ("30-grana@3",       "A", r"mes a mes",                               0.0),
 ("58-dividendo-multa","A", r"dividendo entrando para pagar",          0.0),
 ("31-cupom@3",       "A", r"baixa o grana",                           0.0),
 ("x-tracker-shorts", "B", r"nao desmontou",                           0.0),
 ("59-ia-esfria",     "A", r"quem compra o cobre",                     0.0),
 ("60-pasto",         "A", r"o pasto do dono do boi",                  0.0),
 ("19-sobra@2",       "A", r"lembra da sobra",                         0.0),
 ("34-queda30@2",     "A", r"o cobre sai de quase 7",                  0.0),
 ("61-ero-vs-cobre",  "A", r"sobe mais que o metal",                   0.0),
 ("17-boi-acougue@3", "A", r"tira o cobre da terra ou",                0.0),
 ("d2-pmam-2t26@2",   "B", r"zero la do comeco",                       0.0),
 ("24-vale-4x@2",     "A", r"na vale, para cada real",                 0.0),
 ("p-copx-holdings",  "B", r"espalhado em 40",                         0.0),
 ("35-metade@2",      "A", r"paga primeiro",                           0.0),
 ("62-burry-barsi",   "A", r"burry comprou o boi",                     0.0),
 ("12-550-zero@3",    "A", r"proximo balanco",                         0.0),
 ("63-gargalo",       "A", r"limitacoes da inteligencia",              0.0),
 ("64-quem-onde",     "A", r"ta escolhendo a mineracao",              0.0),
 ("ss-archive",       "B", r"escreveu no subst",                       0.0),
 # ---------- fotos reais + prints de ETF/BDR/cotacao (Denis 27/09) ----------
 ("p-pmam3",          "B", r"infelizmente, ela esta na recuperacao",   0.0),
 ("foto-ero-mina",    "B", r"cavadinha",                               0.0),
 ("foto-paranapanema@2","B", r"santo andre",                           0.0),
 ("foto-ero-mina2",   "B", r"lucro da ero",                            0.0),
 ("p-ero-quote",      "B", r"bolsa de toronto",                        0.0),
 ("p-vale3",          "B", r"vale faz tudo pouquinho",                 0.0),
 ("foto-vale",        "B", r"so que o boi divide",                     0.0),
 ("p-cper",           "B", r"abaixo do proprio metal",                 0.0),
 ("p-copx",           "B", r"fundo de indice",                         0.0),
 ("p-bcpx39",         "B", r"recibo negociado",                        0.0),
 ("foto-cobre-fio",   "B", r"afiacao e o cobre",                       0.0),
 ("foto-datacenter",  "B", r"data center fica pronto",                 0.0),
 ("foto-datacenter@2","B", r"principalmente data center",              0.0),
 ("foto-vale-cobre",  "B", r"niquel e cobre,",                         0.0),
]
