# B-roll do "Cotista recusou a cota nova do TRXF11" (gravado 29/09) — molde Burry (27/09)
# (id, peca, ancora regex, atraso[, depois])  peca A = cartela | B = print (manchete / documento)
# ancora = regex no texto do segmento do RENDER (sem acento, minusculo)
# Denis (29/09): "parecido com o do Burry, animacoes, bem dinamico, quanto mais prints melhor".
# Prints (B) entram no bloco PRINTS la embaixo depois que prints/prints.json existir.
PECAS = [
 # ---------- BLOCO 0 — gancho ----------
 ("01-pediu-5bi",      "A", r"pediu 5 bilhoes",                         0.0),
 ("02-deram-40mi",     "A", r"deram 40 milhoes",                        0.0),
 ("03-chapeu",         "A", r"passou o chapeu",                         0.0),
 ("04-outro-comprador","A", r"achou outro comprador",                   0.0),
 ("05-guarda-093",     "A", r"93 centavos por mes",                     0.0),
 ("06-tres-casos",     "A", r"pensa em comprar mais em vender",         0.0),
 # ---------- BLOCO 1 — a queda ----------
 ("07-tombo",          "A", r"tres semanas depois",                     0.0),
 ("08-oferta-anuncio", "A", r"anunciou essa oferta",                    0.0),
 ("09-desistiu-3bi",   "A", r"3 bilhoes em predio",                     0.0),
 ("10-novela",         "A", r"ultimo capitulo",                         0.0),
 ("11-comprou-de-novo","A", r"voltou as compras",                       0.0),
 ("12-cota-hoje",      "A", r"fim de setembro, a cota",                 0.0),
 ("13-ninguem-cancelou","A", r"ainda nao foi cancelada",                0.0),
 # ---------- BLOCO 2 — a ficha do caixa ----------
 ("14-preco-fixo",     "A", r"continuou custando",                      0.0),
 ("15-quermesse",      "A", r"da quermesse e a cota",                      0.0),
 ("16-quantas",        "A", r"quantas fichas",                          0.0),
 ("18-festa-junina",   "A", r"comprou ficha demais",                    0.0),
 ("17-dist-22",        "A", r"distancia entre o caixa",                 0.0),
 # ---------- BLOCO 3 — encerramento ----------
 ("19-papel-1009",     "A", r"papel que diz isso",                      0.0),
 ("20-le-texto",       "A", r"le o texto",                              0.0),
 ("21-profissional",   "A", r"10 milhoes de reais mercado",                     0.0),
 ("22-ate-fev",        "A", r"vai ate fevereiro",            0.0),
 ("23-so-convidados",  "A", r"so para convidados",                      0.0),
 # ---------- BLOCO 4 — quem paga com predio ----------
 ("24-fluxo-predio",   "A", r"o fundo quer comprar um predio",          0.0),
 ("25-compensacao",    "A", r"nome de cartorio",                        0.0),
 ("26-pastel",         "A", r"barraca de pastel",                       0.0),
 ("27-engenhoso",      "A", r"justica seja feita",                      0.0),
 ("28-1bi-3dias",      "A", r"em tres dias",                            0.0),
 # ---------- BLOCO 5 — a conta da Berrini ----------
 ("29-berrini",        "A", r"custaram uns 250",                        0.0),
 ("30-cotas-haaa",     "A", r"na parte paga com cota",                  0.0),
 ("31-conta-22mi",     "A", r"22 reais vezes",                          0.0),
 ("32-sacola",         "A", r"sacola de ficha",                         0.0),
 ("33-tres-respostas", "A", r"tres respostas possiveis",                0.0),
 ("34-r1-preco",       "A", r"a primeira delas",                        0.0),
 ("35-r2-prazo",       "A", r"corrigido pela inflacao",                 0.0),
 ("36-r3-protecao",    "A", r"protecao de preco",                       0.0),
 ("37-3-por-cota",     "A", r"no pior caso",                            0.0),
 ("38-contrario",      "A", r"vale o contrario",                        0.0),
 ("39-nao-crime",      "A", r"e crime",                                 0.0),
 # ---------- PUBLI ----------
 ("40-imposto",        "A", r"menos de 20 mil",                         0.0),
 ("41-darf",           "A", r"quem emite",                              0.0),
 ("42-prejuizo",       "A", r"vendeu no prejuizo",                      0.0),
 ("43-grana",          "A", r"todas as suas guias",                     0.0),
 ("44-multa",          "A", r"a multa, juros",                       0.0),
 ("43-grana@2",        "A", r"todo mes, a partir de agora",              0.0),
 ("45-cupom",          "A", r"cupom desenrola",                         0.0),
 ("45-cupom@2",        "A", r"o cupom e desenrola",                     0.0),
 # ---------- BLOCO 6 — o lado do fundo ----------
 ("46-predios-bons",   "A", r"galpao alugado",                          0.0),
 ("47-div-093",        "A", r"0,93 por cota todo mes",                  0.0),
 ("48-conta-ninguem",  "A", r"quase ninguem faz",                       0.0),
 ("49-entra-sai",      "A", r"centavos entram",                         0.0),
 ("50-cap-rate",       "A", r"cap rate de 10%",                         0.0),
 ("51-galpao-es",      "A", r"8,6% ao ano",                             0.0),
 ("51-galpao-es@2",    "A", r"dividido pelos 12 meses",                 0.0),
 ("52-iguatemi",       "A", r"cada cota nova usada ali",                0.0),
 ("54-cdi",            "A", r"corrigidas pelo cdi",                     0.0),
 ("55-puxa-baixo",     "A", r"puxa o dividendo",                        0.0),
 ("56-brc",            "A", r"vendeu 15 imoveis",                       0.0),
 # ---------- BLOCO 7 — a conta da ficha ----------
 ("57-conta-ficha",    "A", r"em tres passos",                          0.0),
 ("58-quem-pagou",     "A", r"foi o preco do predio, foi o prazo",      0.0),
 ("59-berrini-deu",    "A", r"na berrine, a conta da ficha",           0.0),
 # ---------- BLOCO 8 — comprar, vender ou ficar ----------
 ("60-093-volta",      "A", r"la no comeco e e por ele",                    0.0),
 ("61-vp",             "A", r"abaixo do valor patrimonial",             0.0),
 ("63-aluguel-venda",  "A", r"uma parte e aluguel",                     0.0),
 ("62-15pct",          "A", r"15% ao ano",                              0.0),
 ("49-entra-sai@2",    "A", r"repete a conta",                          0.0),
 ("64-trava-45",       "A", r"45 dias",                                 0.0),
 ("65-um-quarto",      "A", r"um quarto de desconto",                   0.0),
 ("66-ficar",          "A", r"vai ficar, fala vou ficar",               0.0),
 ("67-quem-fecha",     "A", r"nao fecham a conta",                      0.0),
 # ---------- cauda ----------
 ("68-montanha-russa", "A", r"super bem",                               0.0),
 ("69-susto",          "A", r"nao quer ter susto",                      0.0),
 ("70-comenta",        "A", r"voce e cotista do tr",                   0.0),

 # ---------- PRINTS (agente 29/09: 85 prints, fnet + Investidor10 + manchetes + Receita) ----------
 ("d1c-27ago-preferencia-40mi",     "B", r"nao deu nem 1%",                      0.0),
 ("m02-radar-despenca",             "B", r"a oferta ta morta",                   0.0),
 ("d3d-berrini-compensacao",        "B", r"o jeito que esse comprador paga",     0.0),
 ("p2-i10-dividendos-093",          "B", r"esta em jogo",                        0.0),
 ("p1-i10-cotacao-grafico-6m",      "B", r"tombo de agosto",                     0.0),
 ("m03-infomoney-queda-20",         "B", r"perenidade pura",                     0.0),
 ("d1a-13a-5bi",                    "B", r"era o dinheiro para sair comprando",  0.0),
 ("m11b-sd-queda-27-no-ano",        "B", r"voce deve estar triste",              0.0),
 ("m04-sd-desiste-malzoni",         "B", r"desistir de quanto",                  0.0),
 ("m05-infomoney-cyrela-2bi",       "B", r"cota voltou a subir de novo",         0.0),
 ("m11-sd-283bi",                   "B", r"assinou outros 3 bilhoes",            0.0),
 ("d1b-13a-preco-94",               "B", r"preco que nao se mexe",               0.0),
 ("d2i-fnet-entrega-10set-2034",    "B", r"fato relevante no site da bolsa",     0.0),
 ("d2h-fnet-rotulo-anuncio-encerramento","B", r"nome do papel e o anuncio",      0.0),
 ("d2a-10set-titulo",               "B", r"comeca outra rodada",                 0.0),
 ("d1d-27ago-titulo",               "B", r"o que encerrou foi a vez",            1.5),
 ("m06-empiricus-948-sobras",       "B", r"chance maravilhosa",                  0.0),
 ("d2b-10set-sobras-948",           "B", r"antes de todo mundo",                 0.0),
 ("d2c-10set-investidores-profissionais","B", r"essa chance acabou o que o papel abre", 0.0),
 ("d2d-10set-restam-52mi",          "B", r"ano que vem ou ate pelo menos",       0.0),
 ("m06b-empiricus-investidores-profissionais","B", r"que derrubou a cota, que fez voce chorar", 0.0),
 ("d4k-logrecife-75mi",             "B", r"paga o predio com a cota nova",       0.0),
 ("d4k2-logrecife-compensados",     "B", r"comunicado oficial",                  0.0),
 ("d4c-viana-compensados-texto",    "B", r"a traducao",                          0.0),
 ("d4j-hire11-compensacao-82mi",    "B", r"uma divida paga a outra",             0.0),
 ("d4b-viana-compensados-337mi",    "B", r"daqueles 3 bilhoes em setembro",      0.0),
 ("d4f-brf-compensados-93mi",       "B", r"um bilhao e cem milhoes",             0.0),
 ("m15-clubefii-condicoes",         "B", r"promessa assinada",                   0.0),
 ("d3a-berrini-titulo",             "B", r"um dos negocios que ja fechou",       0.0),
 ("d3c-berrini-thera",              "B", r"escritorios na avenida berrin",       0.0),
 ("p3-i10-haaa11",                  "B", r"quem vendeu foi outro fundo",         0.0),
 ("d3f-berrini-parcela-inicial-95mi","B", r"uma parte foi paga com cota nova",   0.0),
 ("d3e-berrini-1010000-cotas",      "B", r"voce ja tem os dois numeros",         0.0),
 ("m07-infomoney-340mi",            "B", r"gastou mais do que o predio vale",    0.0),
 ("d3g-berrini-parcela-final-154mi","B", r"a segunda, o prazo",                  0.0),
 ("d3i-berrini-vence-2033",         "B", r"no mesmo papel da berrin",            2.0),
 ("d3h-berrini-2033-ipca-920",      "B", r"juro gordissimo",                     0.0),
 ("d5a-protecao-titulo",            "B", r"a terceira",                          0.0),
 ("d5b-protecao-205mi",             "B", r"tem um teto",                         0.0),
 ("d5d-protecao-6-18-meses",        "B", r"esse dinheiro sai do fundo",          0.0),
 ("d5c-protecao-ganho-volta",       "B", r"vender a cota com lucro",             1.5),
 ("r1-receita-fii-20",              "B", r"o imposto de renda, tanacao",         0.0),
 ("r2-receita-isencao-so-acoes-ouro","B", r"nao tem esse teto",                  0.0),
 ("r4-receita-compensacao-perdas",  "B", r"esse prejuizo pode abater",           0.0),
 ("r3-receita-darf-ultimo-dia-util","B", r"so se ele ja tiver registrado",       0.0),
 ("m08-sd-340mi-cotas-caem",        "B", r"argumento a favor dele",              0.0),
 ("d4g-brf-titulo",                 "B", r"predios ativos sao bons",             0.0),
 ("d8b-rg-vacancia-05",             "B", r"quase nenhum imovel",                 0.0),
 ("d4d-viana-643mi",                "B", r"pedaco do galpao no espirito",        0.0),
 ("d4a-viana-cap-857",              "B", r"esse pedaco de galpao paga",          0.0),
 ("d8c-rg-rendimento-093",          "B", r"recebe 93 centavos",                  0.0),
 ("d4e-brf-cap-1025",               "B", r"todo anuncio de compra",              0.0),
 ("d4i-iguatemi-titulo",            "B", r"shoppings iguatemi",                  0.0),
 ("m10-mt-iguatemi",                "B", r"assinou essa mesma compra",           0.0),
 ("d11a-nt-yield-on-cost",          "B", r"parcelada para depois",               0.0),
 ("d11b-iguatemi-yoc-1234",         "B", r"passa de 12%",                        0.0),
 ("d4h-iguatemi-306mi-taxa-di",     "B", r"nao sai de graca",                    0.0),
 ("d6d-brc-lucro-051",              "B", r"vendendo imovel",                     0.0),
 ("d9a-dasa-77mi",                  "B", r"ajuda a segurar",                     0.0),
 ("d10b-goiania-41mi",              "B", r"conta do aluguel",                    0.0),
 ("d6e-brc-15-imoveis",             "B", r"vendeu 15 imoveis",                   6.0),
 ("d6c-brc-pago-em-cotas",          "B", r"mesma, mesmo taracateca|mesma taracateca|na hora de vender", 0.0),
 ("m12-infomoney-brc-207",          "B", r"ficha do vizinho",                    0.0),
 ("m13-arevista-brc-detalhe",       "B", r"quanto vale cada ficha dessas",       0.0),
 ("d9c-dasa-11a-emissao-compensacao","B", r"procura no fato relevante",          0.0),
 ("d3e-berrini-1010000-cotas@2",    "B", r"pega quantas cotas",                  0.0),
 ("p1-i10-cotacao-grafico-6m@2",    "B", r"pelo preco da porta",                 0.0),
 ("d3f-berrini-parcela-inicial-95mi@2","B", r"compara esse valor",               0.0),
 ("p1c-i10-vp-9662-vacancia",       "B", r"valor basicamente",                   1.5),
 ("d8a-rg-cota-patrimonial-9661",   "B", r"pela avaliacao do proprio fundo",     0.0),
 ("p1b-i10-pvp-075",                "B", r"de valor patrimonial que esse cara",  0.0),
 ("d2d-10set-restam-52mi@2",        "B", r"caixa da oferta ainda esta aberto",   0.0),
 ("m09-mt-138bi",                   "B", r"continuar pagando predio com cota",   0.0),
 ("d7a-lockup-45-dias-material",    "B", r"quando a trava acaba",                0.0),
 ("d7b-lockup-45-dias-nota-tecnica","B", r"mais gente vendendo na porta",        0.0),
 ("p1c-i10-vp-9662-vacancia@2",     "B", r"vende a r\$72 uma cota",              0.0),
 ("d8a-rg-cota-patrimonial-9661@2", "B", r"no relatorio do fundo",               0.0),
 ("d2e-10set-180-dias",             "B", r"quando a oferta fechar ate fevereiro",0.0),
 ("d2f-10set-encerramento-da-distribuicao","B", r"descobre o tamanho do fundo",  0.0),
 ("m02-radar-despenca@2",           "B", r"anunciou a oferta, derreteu",         0.0),
 ("d12b-desiste-cyrela-31ago",      "B", r"comprou de novo, desistiu",           0.0),
 ("d1a-13a-5bi@2",                  "B", r"vai fechar oferta de 5",              0.0),
 ("d2e-10set-180-dias@2",           "B", r"so em fevereiro",                     0.0, 1300),
]
